=== Randomblock1/altstore/altstore.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://randomblock1.com/altstore/altstore.schema.json",
  "title": "AltSource Schema",
  "description": "A JSON source for AltStore.",
  "type": "object",
  "required": ["name", "identifier", "sourceURL", "apps"],
  "properties": {
    "name": {
      "$id": "#root/name",
      "title": "Name",
      "description": "Name of your source.",
      "type": "string",
      "default": "Example Source",
      "pattern": "^.*$"
    },
    "identifier": {
      "$id": "#root/identifier",
      "title": "Identifier",
      "description": "Unique source identifier.",
      "type": "string",
      "default": "com.example.source",
      "pattern": "^.*$"
    },
    "sourceURL": {
      "$id": "#root/sourceURL",
      "title": "SourceURL",
      "description": "URL of your source's JSON file.",
      "type": "string",
      "default": "https://example.com/altstore",
      "pattern": "^.*$"
    },
    "apps": {
      "$id": "#root/apps",
      "title": "Apps",
      "type": "array",
      "default": [],
      "items": {
        "$id": "#root/apps/items",
        "title": "Items",
        "type": "object",
        "required": [
          "name",
          "bundleIdentifier",
          "developerName",
          "version",
          "versionDate",
          "downloadURL",
          "iconURL",
          "tintColor"
        ],
        "properties": {
          "name": {
            "$id": "#root/apps/items/name",
            "title": "Name",
            "description": "Name of app.",
            "type": "string",
            "default": "Example App",
            "pattern": "^.*$"
          },
          "bundleIdentifier": {
            "$id": "#root/apps/items/bundleIdentifier",
            "title": "BundleIdentifier",
            "description": "Bundle ID of app.",
            "type": "string",
            "default": "com.example.app",
            "pattern": "^.*$"
          },
          "developerName": {
            "$id": "#root/apps/items/developerName",
            "title": "DeveloperName",
            "description": "Name of app developer.",
            "type": "string",
            "default": "John Doe",
            "pattern": "^.*$"
          },
          "version": {
            "$id": "#root/apps/items/version",
            "title": "Version",
            "description": "App version.",
            "type": "string",
            "default": "1.0.0",
            "pattern": "^.*$"
          },
          "versionDate": {
            "$id": "#root/apps/items/versionDate",
            "title": "VersionDate",
            "description": "Date when version released. Can be in the future to display a countdown.",
            "type": "string",
            "default": "2021-12-31T23:59:59-06:00",
            "pattern": "^.*$"
          },
          "versionDescription": {
            "$id": "#root/apps/items/versionDescription",
            "title": "VersionDescription",
            "description": "Version changelog. Can include newlines with \\n.",
            "type": "string",
            "default": "Changelog:\nThing One\nThing Two",
            "pattern": ".*$"
          },
          "downloadURL": {
            "$id": "#root/apps/items/downloadURL",
            "title": "DownloadURL",
            "description": "URL to download app IPA from.",
            "type": "string",
            "default": "https://example.com/app/example.ipa",
            "pattern": "^.*$"
          },
          "localizedDescription": {
            "$id": "#root/apps/items/localizedDescription",
            "title": "LocalizedDescription",
            "description": "App description. Can include newlines with \\n.",
            "type": "string",
            "default": "Example app\nfeaturing\nnewlines",
            "pattern": ".*$"
          },
          "iconURL": {
            "$id": "#root/apps/items/iconURL",
            "title": "IconURL",
            "description": "URL of app icon to display.",
            "type": "string",
            "default": "https://example.com/app/example.png",
            "pattern": "^.*$"
          },
          "tintColor": {
            "$id": "#root/apps/items/tintColor",
            "title": "TintColor",
            "description": "Hex color used to tint the app background.",
            "type": "string",
            "default": "000000",
            "pattern": "^.*$"
          },
          "size": {
            "$id": "#root/apps/items/size",
            "title": "Size",
            "description": "Size of IPA in bytes.",
            "type": "integer",
            "default": 0
          },
          "screenshotURLs": {
            "$id": "#root/apps/items/screenshotURLs",
            "title": "ScreenshotURLs",
            "description": "Array of screenshot URLs",
            "type": "array",
            "default": [],
            "items": {
              "$id": "#root/apps/items/screenshotURLs/items",
              "title": "Items",
              "description": "URL of screenshot image",
              "type": "string",
              "default": "https://example.com/screenshot.png",
              "pattern": "^.*$"
            }
          },
          "permissions": {
            "$id": "#root/apps/items/permissions",
            "title": "Permissions",
            "description": "Optional. Extra permissions this app uses.",
            "type": "array",
            "default": [],
            "items": {
              "$id": "#root/apps/items/permissions/items",
              "title": "Items",
              "type": "object",
              "properties": {
                "type": {
                  "$id": "#root/apps/items/permissions/items/type",
                  "title": "Type",
                  "description": "Can be `photos`, `background-audio`, or `background-fetch`.",
                  "type": "string",
                  "default": "",
                  "pattern": "^.*$"
                },
                "usageDescription": {
                  "$id": "#root/apps/items/permissions/items/usageDescription",
                  "title": "UsageDescription",
                  "description": "Why this app needs that permission.",
                  "type": "string",
                  "default": "",
                  "pattern": "^.*$"
                }
              }
            }
          }
        }
      }
    },
    "news": {
      "$id": "#root/news",
      "title": "News",
      "description": "Array of news items",
      "type": "array",
      "required": ["title", "identifier", "tintColor", "date", "notify"],
      "default": [],
      "items": {
        "$id": "#root/news/items",
        "title": "Items",
        "type": "object",
        "properties": {
          "title": {
            "$id": "#root/news/items/title",
            "title": "Title",
            "description": "Title header",
            "type": "string",
            "default": "Example News Item",
            "pattern": "^.*$"
          },
          "identifier": {
            "$id": "#root/news/items/identifier",
            "title": "Identifier",
            "description": "Unique news identifier",
            "type": "string",
            "default": "com.example.news1",
            "pattern": "^.*$"
          },
          "caption": {
            "$id": "#root/news/items/caption",
            "title": "Caption",
            "description": "Description of news item",
            "type": "string",
            "default": "Hey, look! It's a description!",
            "pattern": ".*$"
          },
          "tintColor": {
            "$id": "#root/news/items/tintColor",
            "title": "TintColor",
            "description": "Background color tint of item",
            "type": "string",
            "default": "3B878D",
            "pattern": "^.*$"
          },
          "imageURL": {
            "$id": "#root/news/items/imageURL",
            "title": "ImageURL",
            "description": "Optional image URL for news item",
            "type": "string",
            "default": "https://example.com/news.png",
            "pattern": "^.*$"
          },
          "date": {
            "$id": "#root/news/items/date",
            "title": "Date",
            "description": "Time to display item, chronologically",
            "type": "string",
            "default": "2021-12-31T23:59:59-06:00",
            "pattern": "^.*$"
          },
          "notify": {
            "$id": "#root/news/items/notify",
            "title": "Notify",
            "description": "Whether to notify user upon recieving",
            "type": "boolean",
            "default": false
          }
        }
      }
    },
    "userInfo": {
      "$id": "#root/userInfo",
      "title": "UserInfo",
      "description": "Optional. Unknown usage.",
      "type": "object",
      "properties": {
        "patreonAccessToken": {
          "$id": "#root/userInfo/patreonAccessToken",
          "title": "PatreonAccessToken",
          "description": "Optional. Unknown usage.",
          "type": "string",
          "default": "",
          "pattern": "^.*$"
        }
      }
    }
  }
}

=== Randomblock1/altstore/apps.json
{
  "apps": [
    {
      "bundleIdentifier": "science.xnu.undecimus",
      "developerName": "Pwn20wnd",
      "downloadURL": "https://unc0ver.dev/downloads/6.0.0/dcf988f66cca8c732decf4d4e4b44eb4fc52582a/unc0ver_6.0.0.ipa",
      "iconURL": "https://github.com/pwn20wndstuff/Undecimus/raw/master/Undecimus/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60%403x.png",
      "localizedDescription": "The most advanced jailbreak tool for iOS 11.0 to iOS 14.3\n\nStable: Utilizing proper and deterministic techniques, jailâ€‹break stability is guaranteed.\nSecure: Utilizing native system sandbox exceptions, security remains intact while enabling access to jailbreak files.\nExtensively Tested: Unc0ver has been extensively tested to ensure it's a seamless experience on all devices.",
      "name": "Unc0ver",
      "screenshotURLs": [
        "https://i.imgur.com/I3aRpPO.jpg",
        "https://i.imgur.com/mERBTaF.jpg"
      ],
      "size": 58380850,
      "subtitle": "The most advanced jailbreak tool",
      "tintColor": "000000",
      "version": "6.0.0",
      "versionDate": "2021-02-26T14:00:00-07:00",
      "versionDescription": "Added support for iOS 14-14.3 for all devices, including iPhone 12!"
    },
    {
      "bundleIdentifier": "com.electrateam.chimera",
      "developerName": "Electra Team",
      "downloadURL": "https://github.com/coolstar/electra-ipas/raw/master/chimera/1.6.2-12.2-12.5.ipa",
      "iconURL": "https://chimera.sh/img/icon.png",
      "localizedDescription": "Jailbreak for all devices, from iOS 12.2 to 12.5.1\n\nNote: Only Nonce setter available on 12.1.2 - 12.3 and 12.4 on A12\nNote: 12.1.3 - 12.5.1 only supported on A7 - A11 devices. All devices supported on 12.0 - 12.1.2\nOn iOS 12 to 12.1.2? Download the IPA from https://chimera.sh instead! (why are you on such an old ios tho)",
      "name": "Chimera",
      "screenshotURLs": [
        "https://chimera.sh/img/jumbotron.png",
        "https://i.imgur.com/dpeAFtg.jpg"
      ],
      "size": 31098621,
      "subtitle": "Your device, your way.",
      "tintColor": "36AEB9",
      "version": "1.6.2",
      "versionDate": "2021-02-06T18:00:00-07:00",
      "versionDescription": "* Fully reliable userspace reboot\n* Sileo icon now shows up reliably on fresh bootstraps\n* uicache runs on rootfs restore and removes jailbreak app icons\n* New Chimera splash screen on userspace reboot"
    },
    {
      "bundleIdentifier": "com.louisanslow.record",
      "developerName": "Louis Anslow",
      "downloadURL": "https://github.com/Randomblock1/randomsource/releases/download/assets/Rewound.ipa",
      "iconURL": "https://pbs.twimg.com/profile_images/1185480705205325825/2pSbjkEz_400x400.jpg",
      "localizedDescription": "Rewound turns your smartphone into your favourite MP3 player from the early 2000s. Access your whole Apple Music library with the swipe of a clickywheel.",
      "name": "Rewound",
      "screenshotURLs": [
        "https://i.imgur.com/SCfCAr0.png",
        "https://i.imgur.com/vPEuaf4.jpg"
      ],
      "size": 5628716,
      "subtitle": "iPod Classic for iPhone",
      "tintColor": "000000",
      "version": "2019.7",
      "versionDate": "2020-03-24T14:00:00-07:00",
      "versionDescription": "Rewound has been pulled from AppStore. Further updates are unlikely."
    },
    {
      "bundleIdentifier": "com.google.ios.youtube",
      "developerName": "Majd Alfhaily",
      "downloadURL": "https://github.com/Randomblock1/randomsource/releases/download/assets/YouTube_v16.8.2_Cercube_v5.2.12.ipa",
      "iconURL": "https://apt.alfhaily.me/cdn/assets/cercube-icon.png",
      "localizedDescription": "Cercube 5 is the ultimate tweak for YouTube app adding tons of features including downloading videos, downloading as audio, disabling ads, background playback, change tab bar layout, and selecting default video quality.\n\nThe tweak works on YouTube and it offers all options available in the original app. Login to your account, view your playlists, subscriptions, trending videos, inbox, and more. \n\nCercube features:\n    - Save videos up to 4K resolution.\n- Save videos as audio only.\n- Set default download quality.\n- Manage and share downloads to any app.\n- Import downloads to Music or Videos.\n- Play YouTube videos using PiP.\n- Set default player quality on WiFi.\n- Set default player quality on 3G/4G.\n- Block all advertisements.\n- Enable background playback.\n- Play in high quality on Mobile Data.",
      "name": "Cercube for YouTube 5",
      "screenshotURLs": [
        "https://apt.alfhaily.me/cdn/assets/cercube-screenshot1.jpg",
        "https://apt.alfhaily.me/cdn/assets/cercube-screenshot2.jpg",
        "https://apt.alfhaily.me/cdn/assets/cercube-screenshot3.jpg",
        "https://apt.alfhaily.me/cdn/assets/cercube-screenshot4.jpg",
        "https://apt.alfhaily.me/cdn/assets/cercube-screenshot5.jpg"
      ],
      "size": 103051129,
      "subtitle": "The YouTube you've always wanted. Ad blocking, video downloading, and more!",
      "tintColor": "DB3020",
      "version": "16.8.2",
      "versionDate": "2021-03-01T14:00:00-07:00",
      "versionDescription": "Updated YouTube base to v16.8.2 and Cercube to v5.2.12"
    },
    {
      "bundleIdentifier": "com.toyopagroup.picaboo",
      "developerName": "Snapchat",
      "downloadURL": "https://github.com/Randomblock1/randomsource/releases/download/assets/Snapchat_v10.79.0_SnapBreak_v1.7.1.ipa",
      "iconURL": "https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/5c/ad/07/5cad0797-e192-6d6d-cf53-cbe4fc063201/source/100x100bb.jpg",
      "localizedDescription": "DOES NOT WORK RIGHT NOW, DO NOT USE. Snapchat with SnapBreak installed. \nThe best tweaked features, like: \nSaving snaps \nViewing snaps but not marking them as read \nUploading media from your photos without the Sent from Camera Roll tag \nJailbreak detection bypass \nDark mode \nAutomatic chat saving \n Multiple accounts + account manager \nAND SO MUCH MORE!",
      "name": "Snapchat++",
      "screenshotURLs": [
        "https://snapbreak.app/img/iphone-presentation-1.png",
        "https://snapbreak.app/img/iphone-presentation-2.png",
        "https://snapbreak.app/img/iphone-presentation-3.png",
        "https://snapbreak.app/img/iphone-presentation-4.png",
        "https://snapbreak.app/img/iphone-presentation-5.png",
        "https://snapbreak.app/img/iphone-presentation-6.png",
        "https://snapbreak.app/img/iphone-presentation-7.png",
        "https://snapbreak.app/img/iphone-presentation-8.png"
      ],
      "size": 95583027,
      "subtitle": "Snapchat with extra features",
      "tintColor": "fffc00",
      "version": "10.79.0.70",
      "versionDate": "2020-04-05T14:00:00-07:00",
      "versionDescription": "SnapBreak Added!"
    },
    {
      "bundleIdentifier": "net.whatsapp.WhatsApp",
      "developerName": "WhatsApp Inc",
      "downloadURL": "https://github.com/Randomblock1/randomsource/releases/download/assets/WhatsApp_v2.20.31_Stalky_v4.1.3_Watusi2_v1.2.36.ipa",
      "iconURL": "https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/a2/07/3f/a2073f3a-1231-5741-24d6-4b31e884dfe2/source/100x100bb.jpg",
      "localizedDescription": "DO NOT USE, DOES NOT WORK (for now). WhatsApp Tweaked includes Stalky and Watusi 2.",
      "name": "WhatsApp Tweaked",
      "screenshotURLs": [
        "http://moreinfo.thebigboss.org/moreinfo/watusi2-1.jpg",
        "http://moreinfo.thebigboss.org/moreinfo/watusi2-2.jpg",
        "http://moreinfo.thebigboss.org/moreinfo/watusi2-3.jpg",
        "http://moreinfo.thebigboss.org/moreinfo/watusi2-4.jpg"
      ],
      "size": 94702097,
      "subtitle": "WhatsApp Tweaked",
      "tintColor": "33DE54",
      "version": "2.20.31",
      "versionDate": "2020-03-24T14:00:00-07:00",
      "versionDescription": "initial upload"
    },
    {
      "bundleIdentifier": "com.spotify.client",
      "developerName": "Spotify",
      "downloadURL": "https://github.com/Randomblock1/randomsource/releases/download/assets/Spotify_v8.5.53_Spos_v8.5.52_Spotilife.ipa",
      "iconURL": "https://repo-cdn.dynastic.co/282547841560215552.79b497042913ea40bdebaab2bf6d32e6-332",
      "localizedDescription": "PROBABLY DOESNT WORK, WAIT FOR UPDATE! Spotilife + Sposify. \nSpotilife: free Spotify Premium. \nSposify: \nThis tweak which adds various enhancements to the Spotify application\nInstructions\n\n    Go into Spotify Settings then tap the Burger Menu Icon for the Sposify Menu\n\nHome Additions\n\n    Connect Access Button\n    Import Your Music\n    Voice Search\n    Verified Profile Badge\n    No Burger Menu Icon on Lockscreen\n\nYour Library Additions\n\n    Show Album & Artist Recommendations\n    Create Playlist New Interface\n    Open Canvas Playlist\n    True Shuffle\n    No Shuffle on Big Play Button\n    Hide Create Playlist\n    Old Artists & Playlists Interface\n    View Artists Offline\n\nNow Playing View Additions\n\n    Long-Press on any Canvas to Save them.\n    Align Text to Top\n    Auto Hide Duration Labels\n    Blackout Mode\n    Canvas Choice Button\n    Canvas Tap\n    Car View\n    Show Statusbar\n    Realtime Lyrics Button\n    Realtime Lyrics Popup\n\nNow Playing View Annoyances\n\n    Disable Genius Lyrics\n    Disable Storylines\n    Disable Canvas\n    Disable Queue Screen Controls\n    Disable Social Listening Section\n\nCanvas Instructions\n\n    Any Canvas you Save will be Saved to an Album called Canvas in Your Photos.",
      "name": "Spotify++",
      "screenshotURLs": [
        "https://repo-cdn.dynastic.co/290772106256318465.d92d68496f31b2913e50b96274549ead-750",
        "https://repo-cdn.dynastic.co/290772143233302529.70634fc05ca98274d0ae747f3ed7f35d-750",
        "https://repo-cdn.dynastic.co/290772183435706369.33de8bb981f38ac620bf6524803c4778-750",
        "https://repo-cdn.dynastic.co/290772213160738817.f2390ff8bd8ef1edad7977d02c2d1ac7-750",
        "https://repo-cdn.dynastic.co/290772240776036353.7722e87a51971d19096d8a64e50a4a32-750",
